version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: mongo:6.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Restore Gradle dependencies cache
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}
            - v1-gradle-cache-

      # Ensure Gradle wrapper is executable
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Build and test with coverage
      - run:
          name: Build & Test with JaCoCo
          command: ./gradlew clean test jacocoTestReport

      # Cache Gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      # Collect test result files
      - run:
          name: Save JUnit Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/test/.*\.xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      # Upload coverage report to Codecov
      - run:
          name: Upload Code Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
