version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: mongo:6.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Restore Maven cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Run Maven build with tests and JaCoCo coverage
      - run:
          name: Build & Run Tests
          command: mvn clean verify

      # Save Maven dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Save test results
      - run:
          name: Save JUnit Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*\.xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      # Upload code coverage to Codecov
      - run:
          name: Upload Code Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
